#

# IIC 1
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_DDC_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_DDC_sda_io]
set_property PACKAGE_PIN W18 [get_ports HDMI_DDC_scl_io]
set_property PACKAGE_PIN W19 [get_ports HDMI_DDC_sda_io]
# IIC 0
#set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]
#set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]
#set_property PACKAGE_PIN N17 [get_ports IIC_0_scl_io]
#set_property PACKAGE_PIN P18 [get_ports IIC_0_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN M17 [get_ports {leds[0]}]
set_property PACKAGE_PIN M19 [get_ports {leds[1]}]
set_property PACKAGE_PIN L19 [get_ports {leds[2]}]
set_property PACKAGE_PIN F16 [get_ports {leds[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[0]}]
set_property PACKAGE_PIN T11 [get_ports {GPIO16_tri_io[0]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO16_tri_io[1]}]
set_property PACKAGE_PIN T12 [get_ports {GPIO16_tri_io[2]}]
set_property PACKAGE_PIN U12 [get_ports {GPIO16_tri_io[3]}]
set_property PACKAGE_PIN R19 [get_ports {GPIO16_tri_io[4]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO16_tri_io[5]}]
set_property PACKAGE_PIN Y16 [get_ports {GPIO16_tri_io[6]}]
set_property PACKAGE_PIN Y17 [get_ports {GPIO16_tri_io[7]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO16_tri_io[8]}]
set_property PACKAGE_PIN Y14 [get_ports {GPIO16_tri_io[9]}]
set_property PACKAGE_PIN T16 [get_ports {GPIO16_tri_io[10]}]
set_property PACKAGE_PIN U17 [get_ports {GPIO16_tri_io[11]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO16_tri_io[12]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO16_tri_io[13]}]
set_property PACKAGE_PIN V12 [get_ports {GPIO16_tri_io[14]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO16_tri_io[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports lrclk_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports lrclk_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports sclk_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports sclk_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports sdata_0_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports sdata_0_out_0]
set_property PACKAGE_PIN H20 [get_ports lrclk_out_0]
set_property PACKAGE_PIN G17 [get_ports lrclk_out_1]
set_property PACKAGE_PIN J20 [get_ports sclk_out_0]
set_property PACKAGE_PIN G18 [get_ports sclk_out_1]
set_property PACKAGE_PIN F19 [get_ports sdata_0_in_0]
set_property PACKAGE_PIN F20 [get_ports sdata_0_out_0]

set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MISO_I_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MOSI_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SCLK_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SS_O_0]
set_property PACKAGE_PIN R14 [get_ports SPI0_MISO_I_0]
set_property PACKAGE_PIN T14 [get_ports SPI0_MOSI_O_0]
set_property PACKAGE_PIN T15 [get_ports SPI0_SCLK_O_0]
set_property PACKAGE_PIN P14 [get_ports SPI0_SS_O_0]

#set_property IOSTANDARD LVCMOS33 [get_ports UART_0_0_rxd]
#set_property IOSTANDARD LVCMOS33 [get_ports UART_0_0_txd]
#set_property PACKAGE_PIN W16 [get_ports UART_0_0_rxd]
#set_property PACKAGE_PIN V16 [get_ports UART_0_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports pwm_l_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_r_out_0]
set_property PACKAGE_PIN Y19 [get_ports pwm_l_out_0]
set_property PACKAGE_PIN Y18 [get_ports pwm_r_out_0]

set_property PACKAGE_PIN U18 [get_ports {TMDS_data_p[0]}]

set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[2]}]

set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
set_property PACKAGE_PIN U14 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports uart_midi_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_midi_txd]
set_property PACKAGE_PIN W16 [get_ports uart_midi_rxd]
set_property PACKAGE_PIN V16 [get_ports uart_midi_txd]

set_property IOSTANDARD LVCMOS33 [get_ports MClk18]
set_property PACKAGE_PIN J18 [get_ports MClk18]
