# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0.xci
# IP: The module: 'zsys_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0.xci
# IP: The module: 'zsys_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/HDMI18.3/HDMI18.3.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_0_0/zsys_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
