set_property IOSTANDARD LVCMOS33 [get_ports PWM_*]
# PWM_L
# PWM_R


set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN U14 [get_ports hdmi_clk_p]

set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[*]}]
set_property PACKAGE_PIN T20 [get_ports {hdmi_data_p[1]}]
set_property PACKAGE_PIN V20 [get_ports {hdmi_data_p[2]}]
set_property PACKAGE_PIN U18 [get_ports {hdmi_data_p[0]}]
create_interface interface_1

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property PACKAGE_PIN T11 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property PACKAGE_PIN T10 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property PACKAGE_PIN T12 [get_ports {gpio_rtl_0_tri_io[2]}]
set_property PACKAGE_PIN U12 [get_ports {gpio_rtl_0_tri_io[3]}]
set_property PACKAGE_PIN R19 [get_ports {gpio_rtl_0_tri_io[4]}]
set_property PACKAGE_PIN V13 [get_ports {gpio_rtl_0_tri_io[5]}]
set_property PACKAGE_PIN Y16 [get_ports {gpio_rtl_0_tri_io[6]}]
set_property PACKAGE_PIN Y17 [get_ports {gpio_rtl_0_tri_io[7]}]
set_property PACKAGE_PIN W14 [get_ports {gpio_rtl_0_tri_io[8]}]
set_property PACKAGE_PIN Y14 [get_ports {gpio_rtl_0_tri_io[9]}]
set_property PACKAGE_PIN T16 [get_ports {gpio_rtl_0_tri_io[10]}]
set_property PACKAGE_PIN U17 [get_ports {gpio_rtl_0_tri_io[11]}]
set_property PACKAGE_PIN V15 [get_ports {gpio_rtl_0_tri_io[12]}]
set_property PACKAGE_PIN W15 [get_ports {gpio_rtl_0_tri_io[13]}]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_0_tri_io[14]}]
set_property PACKAGE_PIN W13 [get_ports {gpio_rtl_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN N17 [get_ports IIC_0_0_scl_io]
set_property PACKAGE_PIN P18 [get_ports IIC_0_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_sda_io]
set_property PACKAGE_PIN W18 [get_ports IIC_1_0_scl_io]
set_property PACKAGE_PIN W19 [get_ports IIC_1_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MISO_I_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MOSI_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SCLK_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SS1_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SS_O_0]
set_property PACKAGE_PIN R14 [get_ports SPI0_MISO_I_0]
set_property PACKAGE_PIN T14 [get_ports SPI0_MOSI_O_0]
set_property PACKAGE_PIN P14 [get_ports SPI0_SS_O_0]
set_property PULLUP true [get_ports IIC_1_0_sda_io]
set_property PULLUP true [get_ports IIC_1_0_scl_io]
set_property PULLUP true [get_ports IIC_0_0_scl_io]
set_property PULLUP true [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN Y18 [get_ports PWM_L]
set_property PACKAGE_PIN Y19 [get_ports PWM_R]
#LED


set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[0]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_rtl_1_tri_o[0]}]
set_property PACKAGE_PIN M19 [get_ports {gpio_rtl_1_tri_o[1]}]
set_property PACKAGE_PIN L19 [get_ports {gpio_rtl_1_tri_o[2]}]
set_property PACKAGE_PIN F16 [get_ports {gpio_rtl_1_tri_o[3]}]

set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[15]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[14]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[13]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[12]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[11]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[10]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[9]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[8]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[7]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[6]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[5]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[4]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[3]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[2]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[1]}]
set_property SLEW FAST [get_ports {gpio_rtl_0_tri_io[0]}]
set_property SLEW FAST [get_ports SPI0_SCLK_O_0]
set_property SLEW FAST [get_ports SPI0_MOSI_O_0]
set_property SLEW FAST [get_ports SPI0_SS_O_0]
set_property PACKAGE_PIN T15 [get_ports SPI0_SCLK_O_0]

set_property PACKAGE_PIN L10 [get_ports Vp_Vn_v_n_0]
set_property PULLDOWN true [get_ports SPI0_SS_O_0]
set_property PACKAGE_PIN T19 [get_ports SPI0_SS1_O_0]
